name: Documentation Autogen
on: [push]
defaults:
  run:
    shell: bash
    working-directory: docs
jobs:
  Compile-Latex-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate PDF
        run: |
          for file in latex; do
            pdflatex -interaction nonstopmode latex/gyro-fern.tex
          done
          