name: Documentation Autogen
on: [push]
defaults:
  run:
    shell: bash
jobs:
  Compile-Latex-Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate PDF
        run: echo "HELLO"
          